module.exports = {
  extends: ['airbnb-base'],
  plugins: ['fp'],
  ignorePatterns: ['node_modules/**/*', 'dist', 'build', 'android', 'ios', 'public'],
  env: {
    browser: true,
    node: true,
    es6: true,
  },
  rules: {
    'no-unused-vars': 'off',
    'consistent-return': 'off',
    'brace-style': ['error', 'stroustrup'],
    'comma-dangle': ['error', 'always-multiline'],
    'arrow-parens': 'off',
    'object-property-newline': ['error', { allowAllPropertiesOnSameLine: true }],
    'object-curly-newline': ['error', { consistent: true }],
    'array-element-newline': ['error', 'consistent'],
    'array-bracket-newline': ['error', { multiline: true }],
    'fp/no-arguments': 'error',
    'fp/no-class': 'error',
    'fp/no-delete': 'error',
    'fp/no-events': 'error',
    'fp/no-get-set': 'error',
    'fp/no-let': 'error',
    'fp/no-loops': 'error',
    'fp/no-mutating-assign': 'error',
    'fp/no-mutating-methods': 'error',
    'fp/no-proxy': 'error',
    'fp/no-this': 'error',
    'fp/no-valueof-field': 'error',
  },
}
